// BOOKING
export const GET_ALL_BOOKING = "GET_ALL_BOOKING"
export const SET_BOOKING_LOADING = "SET_BOOKING_LOADING"
export const SET_BOOKING_ERROR = "SET_BOOKING_ERROR"
export const BOOKING_CHECK_IN = "BOOKING_CHECK_IN"
export const CANCELLED_BOOKING = "CANCELLED_BOOKING"
export const UPDATE_BOOKING = "UPDATE_BOOKING"
export const DELETE_BOOKING = "DELETE_BOOKING"
