// SERVICES
export const GET_ALL_SERVICE = "GET_ALL_SERVICE"
export const SET_SERVICE_LOADING = "SET_SERVICE_LOADING"
export const SET_SERVICE_ERROR = "SET_SERVICE_ERROR"
export const ADD_SERVICE = "ADD_SERVICE"
export const FIND_SERVICE = "FIND_SERVICE"
export const UPDATE_SERVICE = "UPDATE_SERVICE"
export const DELETE_SERVICE = "READ_ALL_SERVICE"
